//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abhs.Model.Access
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("sys_PackageLesson")]
    public partial class SysPackageLesson
    {
        public int spl_ID { get; set; }
        public int spl_spID { get; set; }
        public string spl_Name { get; set; }
        public int spl_State { get; set; }
        public int spl_Difficulty { get; set; }
        public int spl_ItemCount { get; set; }
        public int spl_KnowledgeCount { get; set; }
        public int spl_UseTime { get; set; }
        public int spl_Index { get; set; }
        public string spl_Note { get; set; }
        public string spl_ErrConfig { get; set; }
        public string spl_CheckConfig { get; set; }
        public string spl_Approvaler { get; set; }
        public Nullable<System.DateTime> spl_ApprovalTime { get; set; }
        public System.DateTime spl_CreateTime { get; set; }
        public Nullable<System.DateTime> spl_LastUpdateTime { get; set; }
        public Nullable<int> spl_LastUpdateTeacher { get; set; }
        public string spl_ApprovalMsn { get; set; }
        /// <summary>
        /// 1：普通课时，2复习课，3考试课
        /// </summary>
        public int spl_Type { get; set; }
        /// <summary>
        /// 考试课基础配置
        /// </summary>
        public string spl_TestConfig { get; set; }
        /// <summary>
        /// 考试课抽题规则
        /// </summary>
        //public string spl_TestQuestionRule { get; set; }
        /// <summary>
        /// 考试课具体题
        /// </summary>
        public string spl_TestQuestions { get; set; }
        [NotMapped]
        public List<int> itemList { get; set; }
    }
}
