//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abhs.Model.Access
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("sys_Packages")]
    public partial class SysPackages
    {
        public int sp_ID { get; set; }
        public string sp_Name { get; set; }
        public string sp_Head { get; set; }
        public int sp_HeadId { get; set; }
        public string sp_Teachers { get; set; }
        public string sp_TeacherIds { get; set; }
        public int sp_Type { get; set; }
        public int sp_State { get; set; }
        public int sp_Difficulty { get; set; }
        public string sp_Grades { get; set; }
        public string sp_BookName { get; set; }
        public int sp_Book { get; set; }
        public string sp_Note { get; set; }
        /// <summary>
        /// 封面
        /// </summary>
        public string sp_Cover { get; set; }
        public Nullable<decimal> sp_Price { get; set; }
        public Nullable<decimal> sp_RealPrice { get; set; }
        public int sp_LessonCount { get; set; }
        public System.DateTime sp_CreateTime { get; set; }
        public Nullable<System.DateTime> sp_LastUpdateTime { get; set; }
        public Nullable<int> sp_LastUpdateTeacher { get; set; }
        public string sp_FileList { get; set; }
        [NotMapped]
        public List<int> lessonList { get; set; }
    }
}
