//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abhs.Model.Access
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("sys_PackageLessonItems")]
    public partial class SysPackageLessonItems
    {
        public int spk_ID { get; set; }
        public string spk_Name { get; set; }
        public int spk_spID { get; set; }
        public int spk_splID { get; set; }
        public string spk_KnowledgeIDs { get; set; }
        public int spk_State { get; set; }
        public int spk_Index { get; set; }
        public string spk_BaseNote { get; set; }
        public Nullable<int> spk_BaseTestTime { get; set; }
        public string spk_VideoConfig { get; set; }
        public string spk_PracticeConfig { get; set; }
        public Nullable<System.DateTime> spk_LastUpdateTime { get; set; }
        public Nullable<int> spk_LastUpdateTeacher { get; set; }
        //public string spk_VirtualLabConfig { get; set; }
    }
}
