//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abhs.Model.Access
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("sys_QuestionMark")]
    public partial class SysQuestionMark
    {
        public int m_ID { get; set; }
        public string m_Name { get; set; }
        public Nullable<int> m_Level { get; set; }
        public string m_Code { get; set; }
        public string m_PCode { get; set; }
        public int m_State { get; set; }
        public string m_Remarks { get; set; }
        public int m_Type { get; set; }
        public Nullable<int> m_GradeYear { get; set; }
        public Nullable<int> m_MarkCat { get; set; }
        public string m_Statistics { get; set; }
    }
}
